images:
  samples:
    places:
      - "http://cache3.asset-cache.net/gc/169712426-tokyou-skyline-gettyimages.jpg?v=1&c=IWSAsset&k=2&d=%2FqZzDzSjkyhOxZ25tkQnz3KVN4%2F%2FFspK8vkE1wgbcN4ZKXXvMCHXYy4yT0uVDmUBQVU%2BSNHYHwb6u%2Flgivbn%2Bw%3D%3D"
      - "http://www.aerotravel.co.id/media/upload/ca65f69b9d4ee6a660d4362ca68754d7.jpg"
      - "http://www.wildorchidworldwide.com/images/Scroll/2.jpg"
      - "http://scd.france24.com/en/files/article/image/Tour-Triangle.jpg"
      - "https://resources.attractionsuite.com/stage/sites/43/assets/images/cap-bal-tour-1.jpg?1446451505774"
      - "http://comfortzones.in/wp-content/uploads/2014/10/egypt-TOUR3.jpg"
      - "http://exclusivetouchandaman.com/assets/Tour/9031aa4296ac693cbe51038427afcf39.jpg"
      - "http://www.armscontrolwonk.com/files/2012/12/photo-tour-eiffel-34.jpg"
      - "http://phase1.tourdescanadiens.com/wp-content/themes/tourdescanadiens/images/tour-des-canadiens.jpg"
      - "https://upload.wikimedia.org/wikipedia/commons/2/2f/PublicTMB.jpg"
      - "http://cache-graphicslib.viator.com/graphicslib/thumbs360x240/6391/SITours/versailles-helicopter-tour-from-paris-including-eiffel-tower-fly-over-in-paris-255248.jpg"
      - "http://www.creativeindiajourney.com/img/slider/slider01.jpg"
      - "http://www.planjourneys.com/upload/amazing-europe-tour-package.jpg"
      - "http://www.fattiretours.com/uploads/271/Day-Segway-Hero.jpg"
      - "http://cdn.pariscityvision.com/media/catalog/product/cache/1/image/755x433/9df78eab33525d08d6e5fb8d27136e95/p/s/ps-02-arc-de-triomphe.jpg"
      - "http://www.heritageindiaprivatetours.com/control_panel/TourPackage/4.jpg"
      - "http://tourdulichnga.net/wp-content/uploads/2015/08/tourdulichnga.jpg"
      - "http://www.discoverytravelandtours.com/images/IndiaTourPackages.jpg"
      - "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Tour_de_Sauvabelin_Lausanne.jpg/260px-Tour_de_Sauvabelin_Lausanne.jpg"
      - "http://www.holidayinrajasthan.com/images/golden/golden-triangle-tour1.gif"
owner_types:
  place: "place"
